Failure # 1 (occurred at 2025-10-27_15-29-14)
The actor died because of an error raised in its creation task, [36mray::PPO.__init__()[39m (pid=3201680, ip=192.168.1.104, actor_id=80c6f1ad9e49938d1df9513401000000, repr=PPO(env=marl_cattle_env; env-runners=4; learners=0; multi-agent=True))
  File "/home/ben/.local/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 536, in __init__
    super().__init__(
  File "/home/ben/.local/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 158, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/ben/.local/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 644, in setup
    self.env_runner_group = EnvRunnerGroup(
  File "/home/ben/.local/lib/python3.10/site-packages/ray/rllib/env/env_runner_group.py", line 196, in __init__
    self._setup(
  File "/home/ben/.local/lib/python3.10/site-packages/ray/rllib/env/env_runner_group.py", line 284, in _setup
    spaces = self.get_spaces()
  File "/home/ben/.local/lib/python3.10/site-packages/ray/rllib/env/env_runner_group.py", line 312, in get_spaces
    spaces = self.foreach_env_runner(
IndexError: list index out of range
